[package]
name = "anyhow-error-response"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
saas={ path="../../saas" }
tokio = {version = "1.0", features = ["full"]}
